# This is defined to be a phony target since everything listed in ${SUBDIRS}
# is a directory that is supposed to exist in the current directory.
.PHONY: ${SUBDIRS}

${SUBDIRS}:
	@echo "===> ${DIRPRFX}$@"
	@${MAKE} -C $@ OBJDIR="${OBJDIR}"			\
			OPTIMIZER="${OPTIMIZER}" ${RECTARGET}
	@echo "<=== ${DIRPRFX}$@"

# Using ${SUBDIRS} as the dependencies to 'recursive' allows GNU make to
# build them all in parallel.
recursive: ${SUBDIRS}
