<!--
  This file is specific to the VR Juggler documentation layout and template
  information describing a method's contract.  It inserts a table with the
  heading "Contract" and body containing the method's contract.

  $Id$
 -->

<TABLE BORDER="1" WIDTH="100%">
  <TR>
    <TH COLSPAN="2" BGCOLOR="#6b92b2" ALIGN="LEFT">
      <FONT COLOR="#ffffff" SIZE="-1">Contract</FONT>
    </TH> 
  </TR> 
  {include ../common/contract_table_body.html.inc}
</TABLE>
