# $Id$

DOXYGEN_FILE=		Tweek.doxy
HTML_DOXYGEN_FILE=	$(DOXYGEN_FILE)
LATEX_DOXYGEN_FILE=	Tweek_latex.doxy
MAN_DOXYGEN_FILE=	$(DOXYGEN_FILE)
HTML_OUTPUT_DIR=	html
LATEX_OUTPUT_DIR=	latex

# Fill these in!!  Together, they form the installation prefix.
webroot=	$(HOME)/public_html/phpjug
instdir=	tweek/1.0/programmer.reference

prefix=		$(webroot)/$(instdir)

include ../../../docs/doxygen.mk
