irix:
	gcc -g -I/home/users/kevn/software/irix/include main.cpp -o play -L/home/users/kevn/software/irix/lib -lopenal -lm

linux:
	gcc -g -I/usr/local/include main.cpp -o play -L/usr/local/lib -lopenal -lm
