
!ifndef C2_PATHS
!include ../../lib/makefile.common.win32
!endif



LINK     = link
CC       = cl
LIBEXE   = lib
MKTYPLIB = mktyplib
RC       = rc
MAKE     = nmake

EXE = test

CFLAGS	  = $(BSC) -TP -c -D_X86_=1 -DWIN32 -DWIN -Gz -GX -GR  -nologo  -QIfdiv- \
	$(C2_PATHS)

!ifdef SHIP
CFLAGS = $(CFLAGS) -MT -Ox -Gf -Gy -G3 -W4
!else 
CFLAGS = $(CFLAGS) -MTd -Od -Oi -FR /nologo /MTd /W3 \
  /Z7 /D "WIN32" /D "_DEBUG" /D "_WINDOWS" \
  /Fp"C2Lib.pch" /YX /Fo /Fd /FD 
!endif

# LFLAGS = -align:0x1000 -entry:WinStart -incremental:no -map -nodefaultlib -nologo -fixed -subsystem:windows,4.00
#LFLAGS = -align:0x1000 -incremental:no -nologo -lib
# Bogus!  This has to be / and all caps, or the linker might choke on it
LFLAGS = $(LFLAGS) /FORCE:MULTIPLE /DBGIMPLIB  \
	/LIBPATH:$(VCROOT)\lib 

!ifdef SHIP
#LFLAGS = $(LFLAGS) -merge:.rdata=.text -optidata -opt:ref -warn:3
!else 
#LFLAGS = $(LFLAGS) -warn:2
!endif

!ifdef SHIP
LIBLOC = $(C2ROOT)\lib\OPT.X86.WIN\libc2.lib
!else
LIBLOC = $(C2ROOT)\lib\DBG.X86.WIN\libc2.lib
!endif

OBJECTS = main.obj

$(EXE).exe: $(OBJECTS)
	$(LINK) $(LFLAGS) -out:$(EXE).exe $(OBJECTS) $(LIBLOC)

$(OBJECTS):
	$(CC) $(CFLAGS) $*.C

info::
	@ echo "Info for the make of $(EXE)"
	@ echo "C2_PATHS: $(C2_PATHS)"
	@ echo "OBJS: $(OBJECTS)"


