#! /bin/sh
#
#
# Do cool stuff
# Note: Do not hold Allen accountable for any damages incurred
#

# If the script succeeds, then we fail.
if perl $CVSROOT/CVSROOT/log_verify.pl ${1+"$@"}
then
  exit 0
else
  echo "log_verify: Executed command"
  exit 1
fi

exit 0		# Lets do it!
