#! /bin/sh

# If the script succeeds, then we fail.
if /usr/bin/perl /cvsroot/vrjuggler/CVSROOT/log_verify.pl ${1+"$@"}
then
  exit 0
else
  echo "log_verify: Executed command"
  exit 1
fi

exit 0		# Lets do it!
