/* Generated by Together */

#ifndef CONCRETEDEPCHECKER_H
#define CONCRETEDEPCHECKER_H
#include "jccl/RTRC/DepChecker.h"

/**
 * @stereotype multiple 
 */
class ConcreteDepChecker : public jccl::DepChecker {
public:    

    std::string getCheckerName();

    void canHandle();

    bool depSatisfied();
};
#endif //CONCRETEDEPCHECKER_H
