#!/bin/sh

#setenv PATH /usr/java/bin:$PATH
#setenv JDK_HOME /usr/java


java -DVJ_BASE_DIR=${VJ_BASE_DIR} -classpath ${VJ_BASE_DIR}/bin/VjCfg.jar:/usr/java/lib/classes.zip VjGUI.AppCore fileeditor $1 $2 $3 $4 $5 $6
