#!/bin/sh

${JDK_HOME}/bin/java -DVJ_BASE_DIR=${VJ_BASE_DIR} -classpath ${VJ_BASE_DIR}/bin/VjControl.jar:${VJ_BASE_DIR}/bin/swingall.jar:${JDK_HOME}/lib/classes.zip VjGUI.VjControl $1 $2 $3 $4 $5 $6 $7 $8 $9