/*************** <auto-copyright.pl BEGIN do not edit this line> **************
 *
 * VR Juggler is (C) Copyright 1998, 1999, 2000, 2001 by Iowa State University
 *
 * Original Authors:
 *   Allen Bierbaum, Christopher Just,
 *   Patrick Hartling, Kevin Meinert,
 *   Carolina Cruz-Neira, Albert Baker
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 *************** <auto-copyright.pl END do not edit this line> ***************/
package org.vrjuggler.vrjconfig;

import java.awt.BorderLayout;
import java.awt.event.*;
import java.util.*;
import javax.swing.*;
import org.vrjuggler.vrjconfig.ui.*;
import org.vrjuggler.tweek.beans.loader.BeanJarClassLoader;

/**
 * Provides a control panel view into a config chunk collection.
 */
public class ControlPanelView
   extends JPanel
{
   public ControlPanelView()
   {
      try
      {
         jbInit();
      }
      catch(Exception e)
      {
         e.printStackTrace();
      }

      // Init the icons in the model
      ClassLoader loader = BeanJarClassLoader.instance();
      model.add("Display",   new ImageIcon(loader.getResource("org/vrjuggler/vrjconfig/images/display64.gif")));
      model.add("Simulator", new ImageIcon(loader.getResource("org/vrjuggler/vrjconfig/images/simulator64.gif")));
      model.add("Cluster",   new ImageIcon(loader.getResource("org/vrjuggler/vrjconfig/images/cluster64.gif")));
      model.add("Devices",   new ImageIcon(loader.getResource("org/vrjuggler/vrjconfig/images/devices64.gif")));
      model.add("Audio",     new ImageIcon(loader.getResource("org/vrjuggler/vrjconfig/images/audio64.gif")));
      control.addActionListener(new ActionListener()
      {
         public void actionPerformed(ActionEvent evt)
         {
            Object value = control.getModel().getElementAt(evt.getID());
            JOptionPane.showMessageDialog(ControlPanelView.this, "Selected "+String.valueOf(value));
         }
      });
   }

   /**
    * Autogenerated code for the JBuilder GUI.
    */
   private void jbInit()
      throws Exception
   {
      this.setLayout(baseLayout);
      control.setTitle("Choose a category");
      control.setModel(model);
      this.add(control,  BorderLayout.CENTER);
   }

   //--- JBuilder GUI variables ---//
   private ControlPanel control = new ControlPanel();
   private BorderLayout baseLayout = new BorderLayout();

   /**
    * The data model for the control panel.
    */
   private DefaultControlPanelModel model = new DefaultControlPanelModel();
}
