#include <tweek/idl/Subject.idl>

module networktest
{
   interface WhiteboardSubject : tweek::Subject
   {
      void insertText(in long offset, in long length, in string text);
      void getLastChange(out long offset, out long length, out string text);
      string getAllText();
   };
};
