/* Generated by Together */

#ifndef AUDIOWORKSSOUNDIMPLEMENTATION_H
#define AUDIOWORKSSOUNDIMPLEMENTATION_H
#include "SoundImplementation.h"

class AudioWorksSoundImplementation : public SoundImplementation
{
};


#endif //AUDIOWORKSSOUNDIMPLEMENTATION_H