/* Generated by Together */

#ifndef AUDIOWORKSSOUNDIMPLEMENTATION_H
#define AUDIOWORKSSOUNDIMPLEMENTATION_H
#include "ISoundImplementation.h"
class AudioWorksSoundImplementation : public ISoundImplementation 
{
};
#endif //AUDIOWORKSSOUNDIMPLEMENTATION_H