/* Generated by Together */

#ifndef OPENALSOUNDIMPLEMENTATION_H
#define OPENALSOUNDIMPLEMENTATION_H
#include "ISoundImplementation.h"
class OpenALSoundImplementation : public ISoundImplementation 
{
};
#endif //OPENALSOUNDIMPLEMENTATION_H