/* Generated by Together */

#ifndef STUBSOUNDIMPLEMENTATION_H
#define STUBSOUNDIMPLEMENTATION_H
#include "ISoundImplementation.h"
#include "SoundImplementation.h"
class StubSoundImplementation : public SoundImplementation
{
};
#endif //STUBSOUNDIMPLEMENTATION_H