<!--
  A simple table with the description (both brief and detailed) of the
  current member.  The layout is for the VR Juggler documentation, but it
  could be modified to be used elsewhere.

  $Id$
 -->

<TABLE BORDER="1" WIDTH="100%">
  <TR>
    <TH BGCOLOR="#6b92b2" ALIGN="LEFT">
      <FONT COLOR="#ffffff" SIZE="-1">Description</FONT>
    </TH>
  </TR>
  {include ../common/descr_table_body.html.inc}
</TABLE>
