<!--
  This fills in the heading for a detailed description of a constructor or
  method.  It provides an anchor for external linking directly to this
  entry in the detailed listing.
  This file is specific to the VR Juggler documetnation layout.
 -->

<TR>
  <TH ALIGN="LEFT" BGCOLOR="#4682b4">
    {nolink true}
    <H2><A NAME="{memberef}">
      <FONT COLOR="#ffffff">{mname}</FONT>
    </A></H2>
    {nolink false}
  </TH>
</TR>
