/* Generated by Together */

#ifndef OPENALSOUNDIMPLEMENTATION_H
#define OPENALSOUNDIMPLEMENTATION_H
#include "SoundImplementation.h"
class OpenALSoundImplementation : public SoundImplementation
{
};
#endif //OPENALSOUNDIMPLEMENTATION_H