/* Generated by Together */

#ifndef SOUNDFACTORY_H
#define SOUNDFACTORY_H
#include "ISoundImplementation.h"
class SoundFactory : public vpr::Singleton
{
public:
private:    

    /**
     * @clientCardinality 0..* 
     */
    ISoundImplementation lnkISoundImplementation;
};
#endif //SOUNDFACTORY_H