/* Generated by Together */

#ifndef FLOATSUBJECTIMPL_H
#define FLOATSUBJECTIMPL_H
#include "SubjectImpl.h"
#include "FloatSubject.h"

class FloatSubjectImpl : public tweek::SubjectImpl, POA_example::FloatSubject
{
public:

    FloatSubjectImpl();

    float getValue();

    void setValue(float);
};
#endif //FLOATSUBJECTIMPL_H