/* Generated by Together */

#include "userPfApp.h"
void userPfApp::getScene(){}
void userPfApp::initScene(){}
void userPfApp::postFrame(){}
void userPfApp::intraFrame(){}
void userPfApp::preFrame(){}
void userPfApp::apiInit(){}
void userPfApp::init(){}
