/* Generated by Together */

#include "userOglApp.h"
void userOglApp::contextPreDraw(){}
void userOglApp::contextInit(){}
void userOglApp::draw(){}
void userOglApp::postFrame(){}
void userOglApp::intraFrame(){}
void userOglApp::preFrame(){}
void userOglApp::apiInit(){}
void userOglApp::init(){}
