/* Generated by Together */

#ifndef USERPFAPP_H
#define USERPFAPP_H
class userPfApp : public vrj::PfApp {
public:    

    void init();

    void apiInit();

    void preFrame();

    void intraFrame();

    void postFrame();

    void initScene();

    void getScene();
};
#endif //USERPFAPP_H
