/****************** <SNX heading BEGIN do not edit this line> *****************
 *
 * sonix
 *
 * Original Authors:
 *   Kevin Meinert, Carolina Cruz-Neira
 *
 * -----------------------------------------------------------------
 * File:          $RCSfile$
 * Date modified: $Date$
 * Version:       $Revision$
 * -----------------------------------------------------------------
 *
 ****************** <SNX heading END do not edit this line> ******************/

/*************** <auto-copyright.pl BEGIN do not edit this line> **************
 *
 * VR Juggler is (C) Copyright 1998-2003 by Iowa State University
 *
 * Original Authors:
 *   Allen Bierbaum, Christopher Just,
 *   Patrick Hartling, Kevin Meinert,
 *   Carolina Cruz-Neira, Albert Baker
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 *************** <auto-copyright.pl END do not edit this line> ***************/

/* Generated by Together */

#ifndef SONIX___H
#define SONIX___H

#include <snx/snxConfig.h>

#include <stdlib.h>
#include <string>
#include <gmtl/Matrix.h>
#include <vpr/Util/Singleton.h>

#include "snx/SoundInfo.h"
#include "snx/SoundImplementation.h"
#include "snx/SoundAPIInfo.h"


namespace snx
{

class SNX_CLASS_API sonix
{
protected:
   /** Default constructor. */
   sonix() : mImplementation( NULL )
   {
   }

   /** Virtual destructor. */
   virtual ~sonix();

public:

   /**
    * Triggers a sound.
    *
    * @pre alias does not have to be associated with a loaded sound.
    * @post If it is, then the loaded sound is triggered.  If it isn't, then
    *       nothing happens.
    *
    * @param alias Alias of the sound to trigger, and number of times to play,
    *              -1 to repeat infinately, 1 (single shot) is default.
    */
   virtual void trigger( const std::string& alias, const int& repeat = 1 );
   
   /**
    * Is the sound currently playing?
    */
   virtual bool isPlaying( const std::string& alias );

   /**
    * When sound is already playing then you call trigger,
    * Does the sound restart from beginning?
    */
   virtual void setRetriggerable( const std::string& alias, bool onOff );

   /**
    * Is the sound retriggerable?
    */
   virtual bool isRetriggerable( const std::string& alias );

   /**
    * Stops the sound.
    *
    * @param alias Alias of the sound to be stopped.
    */
   virtual void stop( const std::string& alias );

   /**
    * Pause the sound, use unpause to return playback where you left off.
    */
   virtual void pause( const std::string& alias );

   /**
    * Resumes playback from a paused state.  Does nothing if sound was not
    * paused.
    */
   virtual void unpause( const std::string& alias );
   
   /** If the sound is paused, then return true. */
   virtual bool isPaused( const std::string& alias );
   
   /**
    * Ambient or positional sound.
    * Is the sound ambient: attached to the listener, doesn't change volume
    * when listener moves.
    * Or is the sound positional: changes volume as listener nears or retreats.
    */
   virtual void setAmbient( const std::string& alias, bool setting = false );

   /** Is the sound ambient? */
   virtual bool isAmbient( const std::string& alias );

   /**
    * Alters the frequency of the sample.
    * 1 is no change.
    * < 1 is low.
    * > 1 is high.
    */
   virtual void setPitchBend( const std::string& alias, float amount );

   /** Effect volume.  Set to a value between [0..1]. */
   virtual void setVolume( const std::string& alias, float amount );
   
   /**
    * Effect cutoff.
    * Set to a value between [0..1]... 1 is no change.  0 is total cutoff.
    */
   virtual void setCutoff( const std::string& alias, float amount );
   
   /**
    * Set sound's 3D position.
    *
    * @param alias A name that has been associated with some sound data.
    * @param x     The X coordinate of the sound in 3D OpenGL coordinates.
    * @param y     The Y coordinate of the sound in 3D OpenGL coordinates.
    * @param z     The Z coordinate of the sound in 3D OpenGL coordinates.
    */
   virtual void setPosition( const std::string& alias, const float& x, const float& y, const float& z );

   /**
    * Get sound's 3D position
    *
    * @param alias A name that has been associated with some sound data.
    * @param x     Storage for the X coordinate of the sound in 3D OpenGL
    *              coordinates.
    * @param y     Storage for the Y coordinate of the sound in 3D OpenGL
    *              coordinates.
    * @param z     Storage for the Z coordinate of the sound in 3D OpenGL
    *              coordinates.
    */
   virtual void getPosition( const std::string& alias, float& x, float& y, float& z );

   /**
    * Sets the position of the listener.
    */
   virtual void setListenerPosition( const gmtl::Matrix44f& mat );

   /**
    * Gets the position of the listener.
    */
   virtual void getListenerPosition( gmtl::Matrix44f& mat );


   /**
    * Changes the underlying sound API to something else.  This function is
    * safe.  It always returns a valid implementation.  It runs in O(1)
    * (constant) time.
    *
    * @pre Sound implementation should be registered
    * @post Underlying API is changed to the requested API name.   If
    *       apiName's implementation is not registered, then underlying API is
    *       changed to the stub version.
    *
    * @param apiName Usually a name of a valid registered sound API
    *                implementation.
    */
   virtual void changeAPI( const std::string& apiName );

   /**
    * Configures the sound API global settings.
    */
   virtual void configure( const snx::SoundAPIInfo& sai );

   /**
    * Configures/reconfigures a sound by associating an alias with the sound
    * data.  Later, this alias can be used to operate on the sound data.
    *
    * Configure: associate a name (alias) to the description if not already
    * done.
    * Reconfigure: change properties of the sound to the descriptino provided.
    *
    * @pre provide an alias and a SoundInfo which describes the sound
    * @post alias will point to loaded sound data
    */
   virtual void configure( const std::string& alias, const snx::SoundInfo& description );

   /**
    * Removes a configured sound.  Any future reference to the alias will not
    * cause an error, but will not result in a rendered sound.
    */
   virtual void remove( const std::string alias );

   /**
    * Call once per sound frame (doesn't have to be same as your graphics
    * frame).
    *
    * @param timeElapsed Time elapsed since the last sound frame.
    */
   virtual void step( const float& timeElapsed );
   
protected:
   snx::ISoundImplementation& impl();

private:
   /** @link dependency */
   /*#  snx::SoundFactory lnkSoundFactory; */

   /** @link aggregation 
    * @clientCardinality 1
    * @supplierCardinality 1*/
   snx::ISoundImplementation* mImplementation;
        
   /** sonix API includes objects of this type
    * @link dependency */
   /*#  snx::SoundInfo lnkSoundInfo; */

   /** @link dependency */
   /*#  snx::SoundAPIInfo lnksnx::SoundAPIInfo; */

   vprSingletonHeader(sonix);
};

} // namespace snx

#endif //SONIX___H
