<!--
  Common class/union/struct description file header.  This defines a table
  that spans the width of the including page with the VR Juggler version and
  some general heading information.
  While this is specific to VR Juggler, it could be modified to be used for
  more general-purpose functionality.
 -->

<TABLE BORDER="0" CELLPADDING="3" WIDTH="100%">
  <TR>
    <TD ALIGN="LEFT" WIDTH="13%" BGCOLOR="#008000">
      <A HREF="http://www.vrac.iastate.edu/" TARGET="_top"><FONT COLOR="#ffffff">VRAC</FONT></A>
    </TD>
    <TD ALIGN="CENTER" WIDTH="65%" BGCOLOR="#008000">
      <FONT COLOR="#ffffff" SIZE="+2">Documentation</FONT>
    </TD>
    <TD ALIGN="RIGHT" BGCOLOR="#008000">
      <FONT COLOR="#ffffff"><a href="http://www.vrjuggler.org/" TARGET="_top"><B><I>VR Juggler</a><BR>
      Release 1.0</I></B></FONT>
      <BR>
    </TD>
  </TR>
</TABLE>

<P>
