<!--
  This file is specific to the VR Juggler documentation layout and template
  information describing a method's contract.  It fills in the current
  method's contract (PRE, POST, MODIFIES and NOTE).
 -->

{if MODIFIES}
  <B>Modifies:</B> {MODIFIES}
  <BR>
{endif}
{if PRE}
  <B>Pre:</B> {PRE}
  <BR>
{endif}
{if POST}
  <B>Post:</B> {POST}
  <BR>
{endif}
{if NOTE}
  <B>Note:</B> {NOTE}
  <BR>
{endif}
