APP_NAME = reconfigApp

C++COMPILER =   CC 
C_COMPILER =    cc
COMPILER =      CC 

LD =            ld

MY_INC_DIR =    -I. -I$(VJ_BASE_DIR)/include
MYLIBS =   -L/usr/lib32 -L$(VJ_BASE_DIR)/lib -lJuggler -lJuggler_ogl -lvpr -ljccl -lgadget


# These are assorted other libraries that must be linked with 
GLLIBS =    -lGLU -lGL 
XLIBS =     -lX11
OTHERLIBS = -lm

LIBS =   $(GLLIBS) $(OTHERLIBS) $(MYLIBS)

INCLUDES = $(MY_INC_DIR)

CFLAGS =   -D__irix__ -N32 -g

OBJS = reconfig.o reconfigApp.o

all: $(APP_NAME)

# Does linking of the files and libraries
$(APP_NAME):    $(OBJS)
		@echo "----------------------------------------  Linking...  ----"
		$(COMPILER) $(CFLAGS) $(OBJS) -o $(APP_NAME) $(LIBS)
		@echo ""
		@echo "\n   >>>  Make is Complete <<<\n"
		@echo ""

# Compiles the files if necessary
.cpp.o:           
	$(C++COMPILER) $(INCLUDES) $(CFLAGS) -o $@ -c $*.cpp

#clean up code
clean:
	rm -f *.o
	rm $(APP_NAME)
	@echo "Squeaky Clean"
