# Accidently Check in the Classes??
# this will restore the default configuration for when 
# the classes accidentally get checked in to cvs.

all: defaultclassfiles

default: defaultclassfiles

defaultclassfiles:
	-@echo "Copying defaults";
	-cp c_class_nav.xml classes/class_nav.xml;
	-cp c_index.html classes/index.html;
