#!gmake

# NOTE: This file is not really part of the build system.
# it's just for the developer's convenience..
# just add your personal build stuff here...

kevin:
	-cd install;
	-kevin.make.pl;
	-cd ..;

allen:
	-cd install;
	-make.allen.pl;
	-cd ..;
