#!gmake

#!!!!!!!!!!!!!!!!!!!!!!!!!
# NOTE: This file is not really part of the build system.
#!!!!!!!!!!!!!!!!!!!!!!!!!

# You should copy the juggler_docs/install/*.make.pl file to YOUR OWN.
# This file is just for the web developer's convenience..


# just add your personal build stuff here...
kevin:
	-cd install;
	-kevin.make.pl;
	-cd ..;

allen:
	-cd install;
	-make.allen.pl;
	-cd ..;
