#include <tweek/idl/Subject.idl>

module RTRCInterface
{

   interface RTRCInterfaceSubject : tweek::Subject
   {
      void add( in string chunkDBString );
      void remove( in string chunkDBString );
      void swap( in string addChunkDBString, in string removeChunkDBString );
      string getChunks();

   };

};
